version: "3"

services:
  web:
    build: .
    image: starter:02 # build the docker image with this name
    env_file: .env
    ports:
      - "3000:3000"
    links:
      - db_mongo
    volumes:
      - .:/usr/src/app/:rw
  db_mongo:
    image: mongo
    ports:
      - "27017:27017"